const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"部门管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBumen"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"职位管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhiwei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"材料类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryCailiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"消费类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianzaocaiwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"进度类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianzaojindu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"图纸类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiangmuTuzhi"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"材料参考管理",
                        "menuJump":"列表",
                        "tableName":"cailiaocankao"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"经费预估管理",
                        "menuJump":"列表",
                        "tableName":"jingfeiyugu"
                    }
                ],
                "menu":"开工准备"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "审核",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目图纸管理",
                        "menuJump":"列表",
                        "tableName":"xiangmuTuzhi"
                    }
                ],
                "menu":"项目图纸管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"财务数据管理",
                        "menuJump":"列表",
                        "tableName":"jianzaocaiwu"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"监造进度管理",
                        "menuJump":"列表",
                        "tableName":"jianzaojindu"
                    }
                ],
                "menu":"监造过程验收"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"材料验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouCailiao"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工艺验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouGongyi"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成果验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouChengguo"
                    }
                ],
                "menu":"质量管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yuangong"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"材料参考管理",
                        "menuJump":"列表",
                        "tableName":"cailiaocankao"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"经费预估管理",
                        "menuJump":"列表",
                        "tableName":"jingfeiyugu"
                    }
                ],
                "menu":"开工准备"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"项目图纸管理",
                        "menuJump":"列表",
                        "tableName":"xiangmuTuzhi"
                    }
                ],
                "menu":"项目图纸管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"财务数据管理",
                        "menuJump":"列表",
                        "tableName":"jianzaocaiwu"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"监造进度管理",
                        "menuJump":"列表",
                        "tableName":"jianzaojindu"
                    }
                ],
                "menu":"监造过程验收"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"材料验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouCailiao"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工艺验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouGongyi"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成果验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouChengguo"
                    }
                ],
                "menu":"质量管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"员工",
        "tableName":"yuangong"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"材料参考管理",
                        "menuJump":"列表",
                        "tableName":"cailiaocankao"
                    }
					,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"经费预估管理",
                        "menuJump":"列表",
                        "tableName":"jingfeiyugu"
                    }
                ],
                "menu":"开工准备"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"项目图纸管理",
                        "menuJump":"列表",
                        "tableName":"xiangmuTuzhi"
                    }
                ],
                "menu":"项目图纸管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"财务数据管理",
                        "menuJump":"列表",
                        "tableName":"jianzaocaiwu"
                    }
					,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"监造进度管理",
                        "menuJump":"列表",
                        "tableName":"jianzaojindu"
                    }
                ],
                "menu":"监造过程验收"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"材料验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouCailiao"
                    }
					,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"工艺验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouGongyi"
                    }
					,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"成果验收管理",
                        "menuJump":"列表",
                        "tableName":"yanshouChengguo"
                    }
                ],
                "menu":"质量管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
